[versions]
agp = "8.9.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.12.0"
constraintlayout = "2.2.0"
navigationFragment = "2.7.7"
navigationUi = "2.8.5"
playServices = "12.0.1"
playServicesMaps = "19.0.0"
places = "4.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version = "2.8.5" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
play-services = { group = "com.google.android.gms", name = "play-services", version.ref = "playServices" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

